Session/11 ThreadBlock
Yamasaki-pan961/flutter-yumemi-training pull request #27
Opened 2023-07-25 03:28 UTC by Yamasaki-pan961

## 課題

close #12 

## 対応箇所

- [ ] xxx

## 動作

| expected | actual |
|----------|--------|
| xxx      | xxx    |

2023-07-25 04:20 UTC, Yamasaki-pan961 reviewed
セルフレビューをしました。

2023-07-25 04:20 UTC, Yamasaki-pan961 commented on lib/feature/day_weather/DAY_WEATHER_STATE_MANAGEMENT.md
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
featureが増えた場合、riverpod_graphで生成後にそれぞれのfeatureディレクトリに分けるのが面倒になりそう

2023-07-25 04:20 UTC, Yamasaki-pan961 commented on lib/feature/day_weather/data/yumemi_day_weather_repository.dart
> +            final response = _yumemiWeather.syncFetchWeather(jsonPayload);
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
`YumemiWeather.syncFetchWeather`を使うように変更し、isolate内で呼び出すように変更しました。

2023-07-25 04:20 UTC, Yamasaki-pan961 commented on lib/feature/day_weather/presentation/presenter/day_weather_provider.dart
> +class DayWeatherApiCallState extends _$DayWeatherApiCallState {
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
初期値がnullの場合にAsyncValueを使用すると処理が複雑になったので、AsyncValueを使わずに実装しました。

2023-07-25 04:20 UTC, Yamasaki-pan961 commented on test/feature/day_weather/presentation/presenter/day_weather_provider_test.dart
> -
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
前に、テスト対象を上書きすると正確にはテストにならないと指摘されていたので修正いたしました。

2023-07-25 04:20 UTC, Yamasaki-pan961 commented on test/feature/day_weather/presentation/view/day_weather_screen_robot.dart
> +    await tester.pump();
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey) 
LoadingDialogが無限アニメーションなので、pump()に変更しました。

2023-07-25 04:37 UTC, Yamasaki-pan961 commented
CIでエラーがでる問題は調査中です。

2023-07-26 12:56 UTC, blendthink requested changes
@Yamasaki-pan961 
いくつかコメントしましたのでご確認お願いします！

2023-07-26 12:56 UTC, blendthink commented on lib/feature/day_weather/DAY_WEATHER_STATE_MANAGEMENT.md
![next-badge](https://img.shields.io/badge/review-next-blueviolet)
確かにですね。。
それも含めて自動化できるよにスクリプト作っておくといいかもですね〜

2023-07-26 12:56 UTC, blendthink commented on lib/feature/day_weather/presentation/presenter/day_weather_provider.dart
> +    }
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
ローディング中に実行しないようにしていてステキです✨

2023-07-26 12:56 UTC, blendthink commented on lib/common/utils/api_call_status.dart
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
こういうものを用意しておくと便利でいいですね！

2023-07-26 12:56 UTC, blendthink commented on lib/common/utils/api_call_status.dart
> +  T? get asValue => whenOrNull(
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg)
個人的には `asValue` だと `null` の値が返ってくるか分かりづらい気がするので、 `AsyncValue ` のように `valueOrNull` とかにしたいなぁと思いました。

2023-07-26 12:56 UTC, blendthink commented on lib/feature/day_weather/presentation/view/day_weather_screen.dart
> +class _LoadingDialog extends StatelessWidget {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
クラス化していてステキです✨

2023-07-26 12:56 UTC, blendthink commented on lib/feature/day_weather/presentation/view/day_weather_screen.dart
> +      current.maybeWhen(
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg)
↓のようにするとよりスッキリしそうです。
```dart
      current.whenOrNull(
        loading: (_) => showDialog<void>(
          barrierDismissible: false,
          context: context,
          builder: (context) => _LoadingDialog(
            key: loadingDialogKey,
          ),
        ),
        loaded: (result) {
          Navigator.of(context).pop();
          result.whenOrNull(
            failure: (errorMessage) => showDialog<void>(
              context: context,
              builder: (context) =>
                  _FetchErrorDialog(errorMessage: errorMessage),
            ),
          );
        },
      );
```

2023-07-26 12:56 UTC, blendthink commented on test/feature/day_weather/presentation/presenter/day_weather_provider_test.dart
> +    test('State retains previous value during loading', () async {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
このテストは大切ですね✨

2023-07-26 12:56 UTC, blendthink commented on test/feature/day_weather/presentation/presenter/day_weather_provider_test.dart
> +      when(useCaseMock.call()).thenAnswer((_) async => resultFailure);
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
ここは振る舞いを定義しているだけかと思いますので、 Arrange のところが適切そうです。
他の箇所も修正お願いします！

2023-07-26 12:56 UTC, blendthink commented on test/feature/day_weather/presentation/presenter/day_weather_provider_test.dart
> +    test('State retains previous value during loading', () async {
![must-badge](https://img.shields.io/badge/review-must-red.svg)
現状、意図したテストコードになっていないようです。
↓のように修正する必要がありそうなので、他の箇所も含めてご確認お願いします！
```dart
    test('State retains previous value during loading', () async {
      // Arrange
      final riverpodTestTools = RiverpodTestTools(
        useCaseMock: useCaseMock,
      );
      final fetchCompleter = Completer<Result<Weather, String>>();

      // 初期値を変更
      final resultSuccess = Result<Weather, String>.success(weather);
      when(useCaseMock.call()).thenAnswer((_) async => resultSuccess);
      await riverpodTestTools.container
          .read(dayWeatherApiCallStateProvider.notifier)
          .fetchWeather();
      expect(
        riverpodTestTools.container
            .read(dayWeatherApiCallStateProvider)
            .asValue,
        resultSuccess,
      );
      
      // ローディング状態に変更
      when(useCaseMock.call()).thenAnswer((_) => fetchCompleter.future);
      final futureResult = riverpodTestTools.container
          .read(dayWeatherApiCallStateProvider.notifier)
          .fetchWeather();
      expect(
        riverpodTestTools.container
            .read(dayWeatherApiCallStateProvider)
            .isLoading,
        isTrue,
      );

      // Act
      final actual = riverpodTestTools.container.read(dayWeatherProvider);
      
      fetchCompleter.complete(resultSuccess);
      await futureResult;

      // 念の為、ローディングが完了しているかを確認
      expect(
        riverpodTestTools.container
            .read(dayWeatherApiCallStateProvider)
            .isLoading,
        isFalse,
      );

      // Assert
      expect(actual, weather);
    });
```

2023-07-27 03:12 UTC, Yamasaki-pan961 reviewed
丁寧なレビューありがとうございます！
ご指摘の箇所を修正いたしました。

2023-07-27 03:12 UTC, Yamasaki-pan961 commented on test/feature/day_weather/presentation/presenter/day_weather_provider_test.dart
> +      when(useCaseMock.call()).thenAnswer((_) async => resultFailure);
確認した限りでは、Actに振る舞いの定義をしているのはここだけのようでしたが、他の箇所にもありますでしょうか？

とりあえず修正いたしました。
92a038b9319d844e0130f1f87e850ea905cc7797

2023-07-27 03:12 UTC, Yamasaki-pan961 commented on lib/feature/day_weather/presentation/view/day_weather_screen.dart
> +      current.maybeWhen(
確かにこちらの方が良いですね！
修正しました。

e75fb7eb277d2106fd5a420fa9b4fc04f8c4cfb8

2023-07-27 03:12 UTC, Yamasaki-pan961 commented on test/feature/day_weather/presentation/presenter/day_weather_provider_test.dart
> +    test('State retains previous value during loading', () async {
おっしゃる通り、前の値がweatherであることの確認が抜けていました。
ご指摘通りにすることで正確なテストになりそうです。

他の箇所を確認し次のように修正いたしました。
13c2b4c438918d7ee4b1209407998ca225b20a73

2023-07-27 03:22 UTC, blendthink commented on test/feature/day_weather/presentation/presenter/day_weather_provider_test.dart
> +      when(useCaseMock.call()).thenAnswer((_) async => resultFailure);
いったん大丈夫です 🙆‍♂️ 
もし他にあれば別途指摘します、、！

2023-07-27 03:33 UTC, blendthink reviewed
コメントしていますが、たいしたことではないので Approve させていただ、、こうかと思いましたが、CIがこけている、、？

2023-07-27 03:33 UTC, blendthink commented on lib/feature/day_weather/presentation/view/day_weather_screen.dart
> +      current.when(
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg)
ここも `whenOrNull` を使ってもいいかなと思いました！

2023-07-27 03:33 UTC, blendthink commented on test/feature/day_weather/presentation/presenter/day_weather_provider_test.dart
> +      // 初期値を変更
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg)
自分が日本語で書いちゃいましたが英語に直しても全然OKだと思います 🙆‍♂️ 
（見直した時にわかりやすくするためにあえて日本語にしているということかもしれないので、修正する必要はありません、、！）

2023-07-27 03:37 UTC, Yamasaki-pan961 commented on test/feature/day_weather/presentation/presenter/day_weather_provider_test.dart
> +      // 初期値を変更
英語で記述するのが難しくてコストかかるなと思っていたので、今回はそのままにしておきました🥲

2023-07-27 04:20 UTC, Yamasaki-pan961 commented
@blendthink 
変更なしのPRを作ってCIを動かしたところエラーが出なかったので、このPRの何処かが悪いみたいです。
https://github.com/Yamasaki-pan961/flutter-yumemi-training/pull/28

2023-07-27 04:22 UTC, blendthink reviewed
@Yamasaki-pan961 
`compute` メソッドを利用したことによって、テスト時のログの形式が変わってしまったようです。。
![image](https://github.com/Yamasaki-pan961/flutter-yumemi-training/assets/32213113/f085f100-2006-4126-a4bb-9c9b76fcfdb2)

テスト時にはログを出力しないようにしたほうがよさそうですね、、！

2023-07-27 04:29 UTC, blendthink commented
調べてみると ↓ とのことなので、そもそも compute メソッドの中でログ出力しないように実装したほうがいろいろと良さそうです、、！
https://github.com/dart-lang/logging/issues/63

2023-07-27 04:47 UTC, Yamasaki-pan961 commented
@blendthink 
ありがとうございます！
isolateが必要な箇所のみcomputeを使用するようにしました。
a5a59da798bcb840b20879785f74f053acadad28

画像のようにレポートを確かめるにはどうすれば良いでしょうか？
<img width="478" alt="image" src="https://github.com/Yamasaki-pan961/flutter-yumemi-training/assets/54800851/940d7dcc-1ce8-4acd-939e-4c60cbee752a">

2023-07-27 04:50 UTC, blendthink commented
@Yamasaki-pan961 
> 画像のようにレポートを確かめるにはどうすれば良いでしょうか？

ワークフローで指定されているコマンドをローカルで実行すればできます🙆‍♂️

2023-07-27 04:52 UTC, blendthink approved these changes
![LGTM](https://image.lgtmoon.dev/216666)

2023-07-27 05:09 UTC, Yamasaki-pan961 commented on lib/feature/day_weather/presentation/view/day_weather_screen.dart
> +      current.when(
修正いたしました！
（指摘されていなかった理由を、`when`である方が明示的に`notLoaded`では何もしないと記述した方が良い？と解釈しちゃってました。次からは疑問に思ったことは質問します！！）

2023-07-27 05:34 UTC, merged